Import  all the required library

In [1]:
import pandas as pd
import pandas_ta as ta
from typing import Optional, List, Callable, Dict
from datetime import datetime
import os, sys
from dotenv import load_dotenv
from kiteconnect import KiteConnect
import json
import yfinance as yf

In [5]:

    # Fetch from yfinance
import yfinance as yf
df = yf.download(
    "Reliance.NS",
    period="90d",
    interval="1h",
    progress=False,
    auto_adjust=False
)

print(df.tail())

Price                        Adj Close        Close         High          Low  \
Ticker                     RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS
Datetime
2025-12-31 05:45:00+00:00  1567.800049  1567.800049  1569.099976  1554.800049
2025-12-31 06:45:00+00:00  1572.500000  1572.500000  1572.699951  1565.300049
2025-12-31 07:45:00+00:00  1573.000000  1573.000000  1575.400024  1570.000000
2025-12-31 08:45:00+00:00  1567.900024  1567.900024  1577.000000  1567.500000
2025-12-31 09:45:00+00:00  1570.500000  1570.500000  1571.000000  1567.900024

Price                             Open      Volume
Ticker                     RELIANCE.NS RELIANCE.NS
Datetime
2025-12-31 05:45:00+00:00  1555.000000      843910
2025-12-31 06:45:00+00:00  1567.699951      687181
2025-12-31 07:45:00+00:00  1572.500000      835096
2025-12-31 08:45:00+00:00  1573.199951     1854338
2025-12-31 09:45:00+00:00  1567.900024      647384

In [30]:
from nsetools import Nse
import pandas as pd

# Initialize NSE
nse = Nse()

# Get top gainers
gainers = nse.get_top_gainers()
df_gainers = pd.DataFrame(gainers)

# Get top losers
losers = nse.get_top_losers()
df_losers = pd.DataFrame(losers)
# df_losers.describe()


df_losers['Difference'] = df_losers['prev_price'] - df_losers['open_price']

df_losers['Difference1'] = df_losers['prev_price'] - df_losers['ltp']


df_losers['Difference2'] = df_losers['prev_price'] - df_losers['high_price']


df_losers.head(10)
#df_losers.difference = df_losers["Prev Close"] - df_losers["Last Price"]


# Display top 10
# print("Top 10 Gainers:")
# print(df_gainers.head(10))

# print("\nTop 10 Losers:")
# print(df_losers.head(10))
#print(df_losers["Adj Close"])

,symbol,series,open_price,high_price,low_price,ltp,prev_price,net_price,trade_quantity,turnover,market_type,ca_ex_dt,ca_purpose,perChange,Difference,Difference1,Difference2
0,TCS,EQ,3240.0,3246.0,3198.5,3210.0,3246.8,-1.13,3362634,108145.00,N,15-Oct-2025,Interim Dividend - Rs 11 Per Share,-1.13,6.8,36.8,0.8
1,TECHM,EQ,1614.8,1614.8,1588.3,1591.0,1604.6,-0.85,729913,11644.74,N,20-Oct-2025,Interim Dividend - Rs 15 Per Share,-0.85,-10.2,13.6,-10.2
2,GRASIM,EQ,2844.5,2864.0,2803.5,2833.0,2841.7,-0.31,327956,9309.98,N,12-Aug-2025,Dividend - Rs 10 Per Share,-0.31,-2.8,8.7,-22.3
3,BAJFINANCE,EQ,990.0,994.2,978.4,986.5,989.3,-0.28,9895270,97386.28,N,16-Jun-2025,Bonus 4:1,-0.28,-0.7,2.8,-4.9
4,INFY,EQ,1621.0,1628.6,1609.2,1617.9,1621.6,-0.23,6538656,105702.61,N,14-Nov-2025,Buy Back,-0.23,0.6,3.7,-7.0
5,SUNPHARMA,EQ,1720.2,1725.6,1715.5,1720.0,1720.2,-0.01,1428439,24572.44,N,07-Jul-2025,Dividend - Rs 5.50 Per Share,-0.01,0.0,0.2,-5.4

In [2]:
# Initialize broker
load_dotenv()
api_key = os.getenv("KITE_API_KEY")
access_token = os.getenv("KITE_ACCESS_TOKEN")
print(f"Using API Key: {api_key}")
print(f"Using Access Token: {access_token}")    

if not api_key or not access_token:
    raise ValueError("Missing credentials in .env!")
kite = KiteConnect(api_key=api_key)
kite.set_access_token(access_token)

Using API Key: 33eafl5xk3z7mts7
Using Access Token: J8bRQ2jOmRm2qdsY3x0ZaTPBQ70vBa8o

In [7]:
historical_data = kite.historical_data(instrument_token=256265,from_date=datetime(2025, 12, 18),to_date=datetime.today(), interval="5minute")

In [8]:
historical_data = pd.DataFrame(historical_data)
historical_data

                        date      open      high       low     close  volume
0  2025-12-18 09:15:00+05:30  25764.70  25827.15  25762.45  25777.75       0
1  2025-12-18 09:20:00+05:30  25777.80  25804.05  25770.20  25796.55       0
2  2025-12-18 09:25:00+05:30  25796.30  25804.35  25780.05  25780.05       0
3  2025-12-18 09:30:00+05:30  25780.15  25795.45  25774.90  25785.30       0
4  2025-12-18 09:35:00+05:30  25785.85  25787.60  25770.80  25774.55       0
..                       ...       ...       ...       ...       ...     ...
70 2025-12-18 15:05:00+05:30  25823.65  25829.75  25807.25  25815.70       0
71 2025-12-18 15:10:00+05:30  25818.40  25825.20  25813.50  25820.40       0
72 2025-12-18 15:15:00+05:30  25821.25  25821.25  25810.30  25818.45       0
73 2025-12-18 15:20:00+05:30  25818.45  25820.25  25812.40  25816.55       0
74 2025-12-18 15:25:00+05:30  25816.70  25826.20  25806.70  25815.65       0

[75 rows x 6 columns]

Get the Hightest High and lowest Low

In [9]:
historical_data.describe()

               open          high           low         close  volume
count     75.000000     75.000000     75.000000     75.000000    75.0
mean   25831.580000  25841.009333  25822.221333  25831.810667     0.0
std       40.938618     38.393374     42.219169     40.295124     0.0
min    25741.050000  25747.750000  25726.300000  25740.750000     0.0
25%    25795.900000  25815.700000  25787.825000  25800.900000     0.0
50%    25842.600000  25851.100000  25826.700000  25843.350000     0.0
75%    25865.575000  25872.825000  25852.800000  25865.575000     0.0
max    25894.150000  25902.350000  25888.750000  25893.850000     0.0

In [10]:
#get the Hightest High and lowest Low for the dataframe
highest_high = historical_data['high'].max()
lowest_low = historical_data['low'].min()
print(f"Highest High: {highest_high}")
print(f"Lowest Low: {lowest_low}")

Highest High: 25902.35
Lowest Low: 25726.3

In [11]:
SortedData=historical_data.sort_values(by='close')

SortedData.head(3)

                       date     open      high      low     close  volume
6 2025-12-18 09:45:00+05:30  25745.1  25747.75  25726.3  25740.75       0
5 2025-12-18 09:40:00+05:30  25776.1  25776.85  25742.6  25745.10       0
9 2025-12-18 10:00:00+05:30  25748.7  25750.70  25736.7  25745.65       0

In [12]:
# Calulate SMA and EMA
historical_data['SMA_20'] = ta.sma(historical_data['close'], length=20)
historical_data['EMA_20'] = ta.ema(historical_data['close'], length=20)
historical_data.tail(3)

,date,open,high,low,close,volume,SMA_20,EMA_20
72,2025-12-18 15:15:00+05:30,25821.25,25821.25,25810.3,25818.45,0,25813.2625,25817.107152
73,2025-12-18 15:20:00+05:30,25818.45,25820.25,25812.4,25816.55,0,25811.8625,25817.054090
74,2025-12-18 15:25:00+05:30,25816.70,25826.20,25806.7,25815.65,0,25810.2350,25816.920367

In [13]:
#calculate RSI
historical_data['RSI_14'] = ta.rsi(historical_data['close'], length=14)
historical_data.tail(3)

,date,open,high,low,close,volume,SMA_20,EMA_20,RSI_14
72,2025-12-18 15:15:00+05:30,25821.25,25821.25,25810.3,25818.45,0,25813.2625,25817.107152,48.990796
73,2025-12-18 15:20:00+05:30,25818.45,25820.25,25812.4,25816.55,0,25811.8625,25817.054090,48.258607
74,2025-12-18 15:25:00+05:30,25816.70,25826.20,25806.7,25815.65,0,25810.2350,25816.920367,47.893467

In [14]:
#super trend
supertrend = ta.supertrend(historical_data['high'], historical_data['low'], historical_data['close'], length=7, multiplier=3.0)

#add supertrend to historical_data
historical_data = pd.concat([historical_data, supertrend], axis=1)
historical_data
#full code above

,date,open,high,low,close,volume,SMA_20,EMA_20,RSI_14,SUPERT_7_3.0,SUPERTd_7_3.0,SUPERTl_7_3.0,SUPERTs_7_3.0
0,2025-12-18 09:15:00+05:30,25764.70,25827.15,25762.45,25777.75,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-12-18 09:20:00+05:30,25777.80,25804.05,25770.20,25796.55,0,NaN,NaN,100.000000,NaN,NaN,NaN,NaN
2,2025-12-18 09:25:00+05:30,25796.30,25804.35,25780.05,25780.05,0,NaN,NaN,93.675738,NaN,NaN,NaN,NaN
3,2025-12-18 09:30:00+05:30,25780.15,25795.45,25774.90,25785.30,0,NaN,NaN,93.809881,NaN,NaN,NaN,NaN
4,2025-12-18 09:35:00+05:30,25785.85,25787.60,25770.80,25774.55,0,NaN,NaN,89.618192,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2025-12-18 15:05:00+05:30,25823.65,25829.75,25807.25,25815.70,0,25816.6000,25816.604305,48.002162,25837.297189,-1.0,NaN,25837.297189
71,2025-12-18 15:10:00+05:30,25818.40,25825.20,25813.50,25820.40,0,25815.1950,25816.965800,49.709557,25837.297189,-1.0,NaN,25837.297189
72,2025-12-18 15:15:00+05:30,25821.25,25821.25,25810.30,25818.45,0,25813.2625,25817.107152,48.990796,25837.297189,-1.0,NaN,25837.297189
73,2025-12-18 15:20:00+05:30,25818.45,25820.25,25812.40,25816.55,0,25811.8625,25817.054090,48.258607,25837.297189,-1.0,NaN,25837.297189
74,2025-12-18 15:25:00+05:30,25816.70,25826.20,25806.70,25815.65,0,25810.2350,25816.920367,47.893467,25837.297189,-1.0,NaN,25837.297189

In [15]:
#candelstick patterns
historical_data['CDL_DOJI'] = ta.cdl_doji(historical_data['open'], historical_data['high'], historical_data['low'], historical_data['close'])
historical_data[['open', 'high', 'low', 'close', 'CDL_DOJI']].tail(3)

        open      high      low     close  CDL_DOJI
72  25821.25  25821.25  25810.3  25818.45       0.0
73  25818.45  25820.25  25812.4  25816.55       0.0
74  25816.70  25826.20  25806.7  25815.65     100.0

In [13]:
#candelstick  patterns - Engulfing pattern


historical_data['CDL_ENGULFING'] = ta.cdl_inside(historical_data['open'], historical_data['high'], historical_data['low'], historical_data['close'])

historical_data.tail(3)

,date,open,high,low,close,volume,SMA_20,EMA_20,RSI_14,SUPERT_7_3.0,SUPERTd_7_3.0,SUPERTl_7_3.0,SUPERTs_7_3.0,CDL_DOJI,CDL_ENGULFING
1047,2025-12-18 15:15:00+05:30,25821.25,25821.25,25810.3,25818.45,0,25813.2625,25817.192578,48.460425,25837.293448,-1.0,NaN,25837.293448,0.0,0.0
1048,2025-12-18 15:20:00+05:30,25818.45,25820.25,25812.4,25816.55,0,25811.8625,25817.131380,47.733660,25837.293448,-1.0,NaN,25837.293448,0.0,100.0
1049,2025-12-18 15:25:00+05:30,25816.70,25826.20,25806.7,25815.65,0,25810.2350,25816.990296,47.371255,25837.293448,-1.0,NaN,25837.293448,100.0,0.0

In [17]:
# Get Ltp data for a specific instrument
ltp_data = kite.ltp("NSE:RELIANCE")
ltp_data['NSE:RELIANCE']['last_price']
ltp_data

{'NSE:RELIANCE': {'instrument_token': 738561, 'last_price': 1544.4}}